blueprint:
  name: Yandex Station Voice Control
  author: to4kin
  homeassistant:
    min_version: "2025.1.0"
  source_url: https://github.com/to4kin/home-assistant/blob/main/blueprints/automation/yandex-station-voice-control.yaml
  description: >
    **Version**: 1.1.0


    Control any entity using voice commands from Yandex Station.
    Configure custom commands for turning on, off, or toggle.
    Supports multiple entities, source station filtering, per-action delays,
    mobile notifications, and TTS confirmation.


    **Requires**: [Yandex Station](https://github.com/AlexxIT/YandexStation) integration (HACS).
  domain: automation
  input:
    # Main Settings
    main_section:
      name: Main Settings
      icon: mdi:target
      collapsed: false
      input:
        target_entities:
          name: ðŸŽ¯ Target Entities
          description: >
            The entities to control with voice commands.
            Supports switch, light, fan, cover, script, etc.
          selector:
            entity:
              multiple: true

        source_stations:
          name: ðŸ”Š Source Stations
          description: >
            Optional. Only listen to commands from these Yandex Stations.
            Leave empty to listen to all stations.
          default: []
          selector:
            entity:
              filter:
                - domain: media_player
              multiple: true

    # Voice Commands
    voice_section:
      name: Voice Commands
      icon: mdi:microphone
      collapsed: false
      input:
        turn_on_command:
          name: â–¶ï¸ Turn On Command
          description: >
            Optional. The command from Yandex Station that will turn on the entities.
            Leave empty to disable.
          default: ""
          selector:
            text:

        turn_on_delay:
          name: â±ï¸ Turn On Delay
          description: Wait this duration before turning on.
          default:
            hours: 0
            minutes: 0
            seconds: 0
          selector:
            duration:

        turn_off_command:
          name: â¹ï¸ Turn Off Command
          description: >
            Optional. The command from Yandex Station that will turn off the entities.
            Leave empty to disable.
          default: ""
          selector:
            text:

        turn_off_delay:
          name: â±ï¸ Turn Off Delay
          description: Wait this duration before turning off.
          default:
            hours: 0
            minutes: 0
            seconds: 0
          selector:
            duration:

        toggle_command:
          name: ðŸ” Toggle Command
          description: >
            Optional. The command from Yandex Station that will toggle the entities.
            Leave empty to disable.
          default: ""
          selector:
            text:

        toggle_delay:
          name: â±ï¸ Toggle Delay
          description: Wait this duration before toggling.
          default:
            hours: 0
            minutes: 0
            seconds: 0
          selector:
            duration:

    # Notifications
    notification_section:
      name: Notifications
      icon: mdi:cellphone-message
      collapsed: true
      input:
        notify_devices:
          name: ðŸ“² Notification Devices
          description: >
            Optional. Select mobile devices to receive notifications.
            Leave empty to disable.
          default: []
          selector:
            device:
              filter:
                - integration: mobile_app
              multiple: true

        notify_title:
          name: âœï¸ Notification Title
          description: Title for mobile notifications.
          default: "Yandex Station"
          selector:
            text:

        notify_message_on:
          name: â–¶ï¸ Notification Message (On)
          description: Custom notification message when turning on.
          default: "Turned on"
          selector:
            text:

        notify_message_off:
          name: â¹ï¸ Notification Message (Off)
          description: Custom notification message when turning off.
          default: "Turned off"
          selector:
            text:

        notify_message_toggle:
          name: ðŸ” Notification Message (Toggle)
          description: Custom notification message when toggling.
          default: "Toggled"
          selector:
            text:

    # TTS Confirmation
    tts_section:
      name: TTS Confirmation
      icon: mdi:account-voice
      collapsed: true
      input:
        tts_entity:
          name: ðŸ—£ï¸ Yandex Station for TTS
          description: >
            Optional. Select Yandex Station media player for voice confirmation.
            Leave empty to disable.
          default: []
          selector:
            entity:
              filter:
                - domain: media_player

        tts_confirm_on:
          name: â–¶ï¸ Confirmation Message (On)
          description: Message to speak when turning on.
          default: "Turned on"
          selector:
            text:

        tts_confirm_off:
          name: â¹ï¸ Confirmation Message (Off)
          description: Message to speak when turning off.
          default: "Turned off"
          selector:
            text:

        tts_confirm_toggle:
          name: ðŸ” Confirmation Message (Toggle)
          description: Message to speak when toggling.
          default: "Toggled"
          selector:
            text:

    # Logging
    logging_section:
      name: Logging
      icon: mdi:notebook-outline
      collapsed: true
      input:
        enable_logbook:
          name: ðŸ““ Enable Logbook
          description: Log actions to Home Assistant logbook.
          default: true
          selector:
            boolean:

variables:
  target_entities: !input target_entities
  source_stations: !input source_stations
  notify_devices: !input notify_devices
  tts_entity: !input tts_entity
  tts_confirm_on: !input tts_confirm_on
  tts_confirm_off: !input tts_confirm_off
  tts_confirm_toggle: !input tts_confirm_toggle
  turn_on_cmd: !input turn_on_command
  turn_off_cmd: !input turn_off_command
  toggle_cmd: !input toggle_command
  enable_logbook: !input enable_logbook
  notify_msg_on: !input notify_message_on
  notify_msg_off: !input notify_message_off
  notify_msg_toggle: !input notify_message_toggle
  notify_title: !input notify_title
  has_notify: "{{ notify_devices | length > 0 }}"
  has_tts: "{{ tts_entity != [] and tts_entity != '' }}"
  has_source_filter: "{{ source_stations | length > 0 }}"
  event_entity: "{{ trigger.event.data.entity_id | default('') }}"
  is_valid_source: "{{ not has_source_filter or event_entity in source_stations }}"
  entity_names: >
    {{ target_entities | map('state_attr', 'friendly_name') | select('string') | join(', ') }}

trigger:
  - platform: event
    event_type: yandex_speaker
    id: turn_on

  - platform: event
    event_type: yandex_speaker
    id: turn_off

  - platform: event
    event_type: yandex_speaker
    id: toggle

condition:
  - condition: template
    value_template: "{{ is_valid_source }}"
  - condition: or
    conditions:
      - condition: and
        conditions:
          - condition: trigger
            id: turn_on
          - condition: template
            value_template: "{{ turn_on_cmd != '' and trigger.event.data.value == turn_on_cmd }}"
      - condition: and
        conditions:
          - condition: trigger
            id: turn_off
          - condition: template
            value_template: "{{ turn_off_cmd != '' and trigger.event.data.value == turn_off_cmd }}"
      - condition: and
        conditions:
          - condition: trigger
            id: toggle
          - condition: template
            value_template: "{{ toggle_cmd != '' and trigger.event.data.value == toggle_cmd }}"

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ turn_on_cmd != '' and trigger.event.data.value == turn_on_cmd }}"
        sequence:
          - delay: !input turn_on_delay
          - action: homeassistant.turn_on
            target:
              entity_id: !input target_entities
          - if:
              - condition: template
                value_template: "{{ enable_logbook }}"
            then:
              - action: logbook.log
                data:
                  name: "Yandex Station"
                  message: "Turned on {{ entity_names }}"
          - if:
              - condition: template
                value_template: "{{ has_tts }}"
            then:
              - action: media_player.play_media
                target:
                  entity_id: "{{ tts_entity }}"
                data:
                  media_content_id: "{{ tts_confirm_on }}"
                  media_content_type: "text"
                continue_on_error: true
          - if:
              - condition: template
                value_template: "{{ has_notify }}"
            then:
              - repeat:
                  for_each: !input notify_devices
                  sequence:
                    - action: "notify.mobile_app_{{ device_attr(repeat.item, 'name') | slugify }}"
                      data:
                        title: "{{ notify_title }}"
                        message: "{{ notify_msg_on }} {{ entity_names }}"
                      continue_on_error: true

      - conditions:
          - condition: template
            value_template: "{{ turn_off_cmd != '' and trigger.event.data.value == turn_off_cmd }}"
        sequence:
          - delay: !input turn_off_delay
          - action: homeassistant.turn_off
            target:
              entity_id: !input target_entities
          - if:
              - condition: template
                value_template: "{{ enable_logbook }}"
            then:
              - action: logbook.log
                data:
                  name: "Yandex Station"
                  message: "Turned off {{ entity_names }}"
          - if:
              - condition: template
                value_template: "{{ has_tts }}"
            then:
              - action: media_player.play_media
                target:
                  entity_id: "{{ tts_entity }}"
                data:
                  media_content_id: "{{ tts_confirm_off }}"
                  media_content_type: "text"
                continue_on_error: true
          - if:
              - condition: template
                value_template: "{{ has_notify }}"
            then:
              - repeat:
                  for_each: !input notify_devices
                  sequence:
                    - action: "notify.mobile_app_{{ device_attr(repeat.item, 'name') | slugify }}"
                      data:
                        title: "{{ notify_title }}"
                        message: "{{ notify_msg_off }} {{ entity_names }}"
                      continue_on_error: true

      - conditions:
          - condition: template
            value_template: "{{ toggle_cmd != '' and trigger.event.data.value == toggle_cmd }}"
        sequence:
          - delay: !input toggle_delay
          - action: homeassistant.toggle
            target:
              entity_id: !input target_entities
          - if:
              - condition: template
                value_template: "{{ enable_logbook }}"
            then:
              - action: logbook.log
                data:
                  name: "Yandex Station"
                  message: "Toggled {{ entity_names }}"
          - if:
              - condition: template
                value_template: "{{ has_tts }}"
            then:
              - action: media_player.play_media
                target:
                  entity_id: "{{ tts_entity }}"
                data:
                  media_content_id: "{{ tts_confirm_toggle }}"
                  media_content_type: "text"
                continue_on_error: true
          - if:
              - condition: template
                value_template: "{{ has_notify }}"
            then:
              - repeat:
                  for_each: !input notify_devices
                  sequence:
                    - action: "notify.mobile_app_{{ device_attr(repeat.item, 'name') | slugify }}"
                      data:
                        title: "{{ notify_title }}"
                        message: "{{ notify_msg_toggle }} {{ entity_names }}"
                      continue_on_error: true

mode: single
